version: '2'
services:
  nginx:
      build: ./nginx
      container_name: nginx
      # network_mode: "host"
      volumes:
        - ~/Work:/data1
      restart: always
      ports:
        - "80:80"
        # - "9000:9000"
        # - "3306:3306"
        # - "6379:6379"
      links:
        - php:php
        - mysql:mysql
        - redis:redis
        - memcached:memcached
        - elasticsearch:elasticsearch
        - rabbitmq:rabbitmq
  php:
      build: ./php5
      container_name: php
      # network_mode: "host"
      volumes:
        - ~/Work:/data1
      restart: always
      ports:
        - "9000:9000"
  mysql:
      build: ./mysql/file
      container_name: mysql
      # network_mode: "host"
      volumes:
        - ~/Work/data/mysql:/var/lib/mysql
        - ~/Work/log:/data1/log
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      restart: always
      ports:
        - "3306:3306"
  redis:
      build: ./redis/file
      container_name: redis
      # network_mode: "host"
      volumes:
        - ~/Work/data/redis:/data
        - ~/Work/log:/data1/log
      restart: always
      ports:
        - "6379:6379"
  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"
  rabbitmq:
    image: rabbitmq:3.6.1-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    volumes:
      - ~/Work/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - ES_CLUSTERNAME=mydevelastic
    command: elasticsearch -Des.config=/usr/share/elasticsearch/data/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana-frontend:
    image: kibana:latest
    container_name: kibana-frontend
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
      
  # logstash-central:
  #   image: logstash:latest
  #   container_name: logstash-central
  #   ports:
  #     - "25826:25826"
  #     - "25826:25826/udp"
  #   volumes:
  #     - ~/Work/logstash/conf:/conf
  #   command: logstash -f /conf/central.conf
  #   links:
  #     - redis:redis
  #     - elasticsearch:db

  # logstash-agent:
  #   image: logstash:latest
  #   container_name: logstash-agent
  #   ports:
  #     - "25827:25827"
  #     - "25827:25827/udp"
  #   volumes:
  #     - ~/Work/logstash/conf:/conf
  #   command: logstash -f /conf/agent.conf
  #   links:
  #     - redis:redis
